# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest
# https://gitlab.com/pages/hugo/blob/registry/Dockerfile

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - deploy

# before_script:

test:
  stage: test
  script:
  - hugo
  except:
  - master

pages:
  stage: deploy
  script:
  - hugo
  - wget -qO- https://gitlab.com/MaxdSre/axd-ShellScript/raw/master/assets/tool/axdsopBoostTool.sh > public/boost.sh
  artifacts:
    paths:
    - public
  only:
  - master
