# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# https://gitlab.com/pages/hugo/blob/registry/Dockerfile
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - deploy

# before_script:

test:
  stage: test
  script:
  - hugo
  except:
  - master

pages:
  stage: deploy
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
