baseURL = "https://axdlog.com"
title = "AxdLog"
# title = "AxdLog - Master Technology, Change Destiny"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 6              # 首页每页显示的文章数
rssLimit = 30             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = "axdlog"      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓
# uglyURLs = true

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
pygmentsUseClasses = true # Use CSS classes to format highlighted code
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

# language support en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"  # Default language to use (if you setup multilingual support)

# [[menu.main]]             # config your menu
#   name = "Home"
#   weight = 5
#   identifier = "home"
#   url = "/"
[[menu.main]]
  name = "Archives"
  weight = 10
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 15
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 20
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "About"
  weight = 25
  identifier = "about"
  url = "/about/"

[langusges]
[languages.en]
  subtitle = "Master Technology, Change Destiny"
  description = "AxdLog - A personal blog focus on GNU/Linux howtos, tutorials, securities and experience sharing."
  weight = 2
  language_str = "English"
[languages.zh]
  subtitle = "掌握技術，改變命運"
  description = "AxdLog的個人Blog，關注GNU/Linux技術，安全和經驗分享。"
  weight = 3
  language_str = "漢文版"
  dateFormatToUse = "2006-01-02"
[[languages.zh.menu.main]]
  name = "歸檔"
  weight = 10
  identifier = "archives"
  url = "/post/"
[[languages.zh.menu.main]]
  name = "標籤"
  weight = 15
  identifier = "tags"
  url = "/tags/"
[[languages.zh.menu.main]]
  name = "分類"
  weight = 20
  identifier = "categories"
  url = "/categories/"
[[languages.zh.menu.main]]
  name = "關於"
  weight = 25
  identifier = "about"
  url = "/about/"

# [[languages.en.menu.main]]
#   name = "Home"
#   weight = 5
#   identifier = "home"
#   url = "/"
#
# [[languages.zh.menu.main]]
#   name = "主页"
#   weight = 5
#   identifier = "home"
#   url = "/zh/"

uglyurls = false
# https://gohugo.io/content-management/urls/#permalink-configuration-values
[permalinks]
  # post = "/:year/:title"
  # post = "/:year/:filename"
  post = "/:year/:slug"
  # slug: the content’s slug (or title if no slug is provided in the front matter)

[author]                  # essential
  name = "MaxdSre"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  # uglyURLs = true          # You must set true after use uglyURLs in site (above). because $.Site.UglyURLs can not import.
  since = "2016"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = false     # if false, Rss feed instead of the summary

  # site info (optional)    # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "AxdLog"      # default: the title value    # 默认值: 上面设置的title值
  # subtitle = "Master Technology, Change Destiny"
  keywords = ["GNU/Linux", "System Administration", "DevOps", "Shell Script", "Python", "Security"]
  # description = "The only thing I can control is myself."
  # description = "AxdLog - A personal blog focus on GNU/Linux howtos, tutorials, securities and experience sharing."

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archive-paginate = 36

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  # dateFormatToUse = "2006-01-02"
  dateFormatToUse = "Jan 2, 2006"

  # show word count and read time ?       # 是否显示字数统计与阅读时间
  moreMeta = true

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe     # 是否启用PhotoSwipe（图片可点击）
  bootcdn = false          # In china. @Deprecated: use [params.publicCDN]    # 是否使用bootcdn(@Deprecated: 请使用[params.publicCDN])
  mathjax = true           # see https://www.mathjax.org/  # 是否使用mathjax（数学公式）

  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key
  tencent_analytics = ""    # Tencent Analytics
  baidu_push = false        # baidu push                  # 百度
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification         # 谷歌

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
    enable = true
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
    gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'

  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = false
    repo = "MaxdSre/maxdsre.github.io"    # The repo to store comments
    issueTerm = "pathname"

  [params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.reward]                                         # 文章打赏
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
    alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

  [params.social]                                         # 社交链接
    # a-email = "mailto:your@email.com"
    b-stack-overflow = "https://stackoverflow.com/users/7040344"
    # c-twitter = "http://localhost:1313/"
    # d-facebook = "http://localhost:1313/"
    e-linkedin = "https://www.linkedin.com/in/mmxxdd/"
    # f-google = "http://localhost:1313/"
    g-github = "https://github.com/MaxdSre"
    # h-weibo = "http://localhost:1313/"
    # i-zhihu = "http://localhost:1313/"
    # j-douban = "http://localhost:1313/"
    # k-pocket = "http://localhost:1313/"
    # l-tumblr = "http://localhost:1313/"
    # m-instagram = "http://localhost:1313/"
    n-gitlab = "https://gitlab.com/MaxdSre"
    # o-goodreads = "http://localhost:1313/"
    # p-coding = "http://localhost:1313/"


# jsonfeed support
# more information: https://github.com/xianmin/hugo-theme-jane/issues/23
# [outputs]
#   home = ["html", "jsonfeed"]
#   page = ["html"]
#
# [outputFormats]
# [outputFormats.jsonfeed]
#   mediaType = "application/json"
#   baseName = "feed"
#   isPlainText = true

# multilingual support example
# [langusges]
# [languages.en]
#   title = "Axdlog - Master Technology, Change Destiny"
#   weight = 1
# [languages.zh-cn]
#   title = "Axdlog - 掌握技術，改變命運"
#   weight = 2
